config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # OAuth Login
  get '/auth/:provider', to: 'sessions#create', as: 'login'
  get '/auth/:provider/callback', to: 'sessions#create'
  if Rails.env.development?
    # this is required for the OmniAuth Developer Strategy
    post '/auth/:provider/callback', to: 'sessions#create'
  end

  # logout
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users, only: [:show, :destroy]
  resources :event_types, only: [:create]
  resources :events, only: [:create]
  resources :sleep, only: [:index, :new, :create]

  # API routes
  resources :activities, only: :index
  get '/events', to: 'events#index'
  # patch '/events/:id', to: 'events#update'
  # patch '/event_types/:id', to: 'event_types#update'
end

app/models/sleep.rb
class Sleep < ActiveRecord::Base
  belongs_to :user

  validates :started_at, :ended_at, :user, presence: true # maintains referential integrity
  validates :started_at, :ended_at,
    numericality: {
      greater_than_or_equal_to: 1_262_304_000_000 # 1/1/2010
    }

  validates :rating,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 10
    },
    format: {
      with: /\A\d+(?:\.\d{0,2})?\z/ # limits it to a scale of 2 (x.xx)
    },
    allow_blank: true
end

app/controllers/sleep_controller.rb
require_relative '../../lib/csv_parser'

class SleepController < ApplicationController
  def index
    user = User.find(session[:user_id])
    render json: user.sleep.order(:started_at).as_json, status: :ok
  end

  def new; end

  def create
    SleepBotCSVParser.create_sleep_records(session[:user_id], file, utc_offset)
    redirect_to user_path(session[:user_id])
    # TODO: add error handling
  end

  private

  def file
    params.require(:file)
  end

  def utc_offset
    params.require(:time_zone).require(:utc_offset)
  end
end

app/views/sleep/_new.html.erb
<%= form_tag sleep_index_path, { multipart: true, class: 'new-sleep hidden popup' } do %>
  <h2>Upload Sleep Data<span class='btn-close'>x</span></h2>

  <div>
    <label> Upload Sleep Bot CSV:
    <%= file_field_tag :file, accept: 'text/csv', required: true %>
    </label>
    <a href='#' class='tooltip'>
      <%= image_tag('info_icon.png', class: 'info-icon', alt: '(info)') %>
      <span>Please go to Sleep Bot to export your data as a CSV.
        <strong>Before exporting your data</strong>, be sure to select the
        appropriate time ranges at the top of the page.
      </span>
    </a>
  </div>

  <div>
    <%= collection_select :time_zone, :utc_offset,
      ActiveSupport::TimeZone.all, :formatted_offset, :to_s,
      { prompt: 'Select Time Zone' }, { required: true }
    %>
  </div>

  <%= submit_tag 'Import' %>
<% end %>